### ISSUE TITLE
Very cool soultion, but do you have same for general gaming GPU?

### ISSUE THREAD

**Issue by dvv101111** [GPUOpen-LibrariesAndSDKs/RapidFire_SDK#1]
So, question in topic. Do you have similiar SDK for capture and encode video for mass market video cards?

**Comment by mrogowsk** [comment]
The limitation of GPUs to the FirePro series for RapidFire comes with the DOPP component used for desktop capturing.

If you can get the desktop textures by other means, for example with the Desktop Duplication API from Microsoft, you can still register these textures with RapidFire and encode them to a H264 stream on all GPUs compatible with AMF.

**Comment by dvv101111** [comment]
@mrogowsk  Thank you for information
