### ISSUE TITLE
Did rfResizeSession function support DX11 ?

### ISSUE THREAD

**Issue by guolu-home** [GPUOpen-LibrariesAndSDKs/RapidFire_SDK#2]
Nice work!
One question, did rfResizeSession function support DX11?  Or will you support this feature? 
Thanks!

**Comment by mrogowsk** [comment]
Support of resizing the session is specific to the encoder used in the session.
Currently the RF_AMF encoder does not have support for resizing but there will be an update soon that will add it.

**Comment by mrogowsk** [comment]
With version 1.1.0.23 RapidFire supports resizing for all encoders and sources, including DX11 textures.
