### ISSUE TITLE
can not use gpu to encode in guest os

### ISSUE THREAD

**Issue by zlxing** [GPUOpen-LibrariesAndSDKs/RapidFire_SDK#5]
Hi,
   I want to use gpu to encode bitmap in my guest os, but failed, the return code is -8.

Here is my test code:
rfStatus = rfDll.rfFunc.rfCreateEncoder(rfSession, uiStreamWidth, uiStreamHeight, RF_PRESET_BALANCED);
    float frameTime = 1.0f/30.0f;

    if (rfStatus != RF_STATUS_OK)
    {
        cerr << "Failed to create HW encoder!" << rfStatus <<  endl;
        rfDll.rfFunc.rfDeleteEncodeSession(&rfSession);
        return -1;
    }

Env:
    Host: AMD 7150 enable sriov
    guest os: have passthrough vgpu, and install gpu driver

What can i do to reslove the problem? 
       thanks.

**Comment by mrogowsk** [comment]
Hi zlxing,

the AMD FirePro S7150 GPUs do not support video encoding in VMs if GPU virtualization is used.
This feature will only be supported on our upcoming RadeonPro GPUs for virtualization.

**Comment by zlxing** [comment]
OK, thanks.
