### ISSUE TITLE
Why is the data I get through the DesktopCapture sample all zero?

### ISSUE THREAD

**Issue by zouwen4321** [GPUOpen-LibrariesAndSDKs/RapidFire_SDK#6]
Why is the data I get through the DesktopCapture sample all zero? My AMD card is Radeon Pro WX5100.

**Comment by mrogowsk** [comment]
Hi,

on workstation GPUs you will have to enable the DOPP capturing feature:

- Open the Radeon Pro settings
- Navigate to System->Hardware
- Get the registry path from the "2D Driver File Path" field
- Set the registry key "KMD_EnableDesktopTexture" in that registry path to 1
- Reboot the system
