### ISSUE TITLE
change resolution in vm, some time get a black bitmap first time

### ISSUE THREAD

**Issue by zlxing** [GPUOpen-LibrariesAndSDKs/RapidFire_SDK#7]
hi

my env:
  AMD S7150 enable sriov
  vm use vgpu

When vm resolution has been changed,  i need to re-create new session. Every thing is ok, but some time after session re-created, i get a black bitmap first time.

why? 

my sample code:
   rfStatus = rfDll.rfFunc.rfEncodeFrame(s_rfFrameSession, 0);
		if (rfStatus == RF_STATUS_OK)
		{
			bool success = (RF_STATUS_OK == rfDll.rfFunc.rfGetSourceFrame(s_rfFrameSession, &uiSourceSize, &pSource));
			success &= (RF_STATUS_OK == rfDll.rfFunc.rfGetEncodedFrame(s_rfFrameSession, &uiDiffSize, &pDifference));
			if (success)
			{
				unsigned int uiStreamWidth2 = GetSystemMetrics(SM_CXSCREEN);
				unsigned int uiStreamHeight2 = GetSystemMetrics(SM_CYSCREEN);
				if (uiStreamWidth2 != uiStreamWidth|| uiStreamHeight2!=uiStreamHeight || uiSourceSize!= uiStreamWidth*uiStreamHeight*4
					|| uiDiffSize!= diffMapWidth*diffMapHeight)
				{
				
					if (!CreateAMDSession(rfDll))
					{
						DEBUG_ERROR("Failed to CreateAMDSession!");
						break;
					}

thanks.

**Comment by mrogowsk** [comment]
Hi,

after the resolution has been changed the internal texture in the driver storing the content of the display is reallocated with the new resolution.

If RapidFire is requesting the texture too early the driver will return a black texture.
To recover from this RapidFire is re-requesting the texture every second for 5 seconds after a session was created or resized.

**Comment by zlxing** [comment]
OK, thanks!
